[package]
name = "superproductivity-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.5"
ratatui = "0.20.1"
serde_json = "1.0.96"
